version: "3.2"

services:
  threshold:
    image: threshold/gateway
    ports:
      - "8080:8080"
      - "9136:9136"
      # Enable this for HTTPS
      # - "8443:8443"
    volumes:
      - type: bind
        source: ./example-apis
        target: /opt/kamara/apis
  grafana:
      image: grafana/grafana:4.6.5
      ports:
        - "3000:3000"
